apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-db
  template:
    metadata:
      labels:
        app: axion-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "axion_user"
            - name: POSTGRES_PASSWORD
              value: "P@ssw01rd@123"
            - name: POSTGRES_DB
              value: "axion_db"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: axion-db
spec:
  selector:
    app: axion-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
